### model
model_name_or_path: qwen_model_path

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: amz_user_thinking
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2.5_7b/amz_user_thinking
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true

### eval
val_size: 0.05
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 500
